select the best pay member
parkfree/free-park pull request #15
Opened 2020-10-28 05:43 UTC by flow174

2020-10-28 06:17 UTC, leonfancy requested changes
- 考虑是否需要修改触发 CheckTask 的先决条件：https://github.com/parkfree/free-park/blob/818d61c0e644829c4ae3d666f8cb10e516de79b0/src/main/java/org/chenliang/freepark/service/CheckTaskManager.java#L84

- 结束 PayTask 的条件需要跟着修改：https://github.com/parkfree/free-park/blob/e08103740feb3bbb5f925a4efe8b9c3364ae85a0/src/main/java/org/chenliang/freepark/service/PayTaskManager.java#L91

这个 Member 选择还是需要仔细考虑下，影响可能会比较大。建议先把和积分相关的 Bug 解决之后再做这个功能，不然后面会比较难修复。现在积分有两个 Bug:
- 假如系统记录的积分是 200，但是如果用户手工在小程序里面用了一些积分，只剩 100，那么我们缴费就会失败。而且如果这个账号是积分最多的账号，每次缴费都会选出这个账号，一直缴费失败。只能等到第二天同步积分之后才会恢复正常。 
- 假如用户提前手动在小程序里面签到，那么程序在签到的时候就会失败，失败之后就不会同步当天最新的积分。那么在自动缴费的时候就可能选不到这个 Member。

2020-10-28 06:17 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/model/entity/Member.java
> +  public boolean isPaid() {
方法名也许用 `isUsedToday()` 更好点。

`LocalDate` 的比较可以用它自己的equals方法。

2020-10-28 06:17 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PaymentService.java
> +    if (!member.isPaid() && parkingFee.getMemberDeductible() == 0) {
假如这个 member 没被用过, MemberDeductible 等于 0, 但是积分200以上，是不是可以用这个 member 缴费？

2020-10-28 06:17 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PaymentService.java
> +    //找出有会员优惠且积分最高的
注释和 `findFirstPayableMember` 方法名不匹配。

2020-10-28 06:17 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PaymentService.java
> +      member = memberRepository.findFirstByEnablePayIsTrueAndTenantOrderByPointsDesc(tenant);
最好用方法名反应上面的注释。

2020-10-28 06:24 UTC, flow174 commented on src/main/java/org/chenliang/freepark/service/PaymentService.java
> +    if (!member.isPaid() && parkingFee.getMemberDeductible() == 0) {
不需要
会员优惠始终是第一优先级，如果不行就会找下一个有会员优惠的或者积分最高的（当然有可能还是会找到他自己，但是这个时候他已经被标记为使用过了）

2020-10-28 06:36 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PaymentService.java
> +    if (!member.isPaid() && parkingFee.getMemberDeductible() == 0) {
我的意思是假如这个 member 没被用过, MemberDeductible 等于 0, 但是积分200以上，你就跳过了这个 member。

2020-11-02 05:48 UTC, leonfancy requested changes
只有两个 log 的小问题，其它感觉没问题了。

2020-11-02 05:48 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PaymentService.java
> +      log.info("refresh all members points, and retry");
现在这里 log 就不应该是 `refresh all members` 了。

还有建议把两条 log 和成一条。假如并发量大的话，写成两条可能在日志文件里面分散开，就看不出因果关系了。

2020-11-02 05:48 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PointService.java
> +      log.info("set member {} points to 0", member.getMobile());
这里也应该把两条log 合成一条，并且日常级别应该是 error.

2020-11-02 06:03 UTC, merged