Auto pay
parkfree/free-park pull request #16
Opened 2020-11-17 01:42 UTC by flow174

2020-11-17 10:25 UTC, leonfancy requested changes

2020-11-17 10:25 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/model/entity/Tenant.java
> +    return "admin".equals(role);
Should be `"ROLE_ADMIN".equals(role)`

2020-11-17 10:25 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PayTaskManager.java
> +    LocalDateTime parkAtTime = Instant.ofEpochMilli(parkAtTimestamp).atZone(ZoneId.systemDefault()).toLocalDateTime();
This is duplicated code.

2020-11-17 10:25 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PayTrigger.java
> +    payTime++;
It's better to use `payCount` instead of `payTime`. 

It better to move the increment of `payTime` to `nextExecutionTime()`.

2020-11-17 10:25 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PayTrigger.java
> +    if ((now.getTime() - parkAtTimestamp) <= MARKET_FREE_TIME) {
有种情况没考虑到，假如用户在停车后59分钟手动交了费，然后在第65分钟启动自动缴费。那么你这里的逻辑就会走到 else 分支中，也就是当前立即执行缴费，但是由于距离上次缴费还没过20分支，这次缴费就会失败。

这也是我为什么在我的算法中始终使用取模后的 t 来比较时间的原因：

```
startTime 缴费任务创建时间（时间点，单位：Date 对象）
parkTime 缴费任务创建时已经停车的时长（单位：分钟）
t = parkTime % 60 （对缴费周期取模，例如 parkTime = 77，那么 t = 17，单位：分钟）
safeGuardTime = 1 (单位：分钟)

0 <= t < 20
第 0 次：startTime + (20 - t) + safeGuardTime
第 n 次：startTime + (60 - t) + 60 * (n - 1) + safeGuardTime

20 <= t < 40
第 0 次：startTime
第 n 次：startTime + (60 - t) + 60 * (n - 1) + safeGuardTime

40 <= t < 60
第 0 次：startTime
第 1 次：startTime + 20 + safeGuardTime
第 n 次：startTime + (60 - t) + 60 * (n - 1) + safeGuardTime
```

2020-11-17 10:25 UTC, leonfancy commented on src/main/java/org/chenliang/freepark/service/PayTrigger.java
> +        return lastScheduledDate.getTime() + MARKET_FREE_TIME;
这里不需要加`payTimeDelay`?

2020-11-17 13:13 UTC, flow174 commented on src/main/java/org/chenliang/freepark/service/PayTrigger.java
> +        return lastScheduledDate.getTime() + MARKET_FREE_TIME;
这里不加，这里的场景是第一次满足支付时间马上支付但是下次整点支付时间还在免费时间内，因此直接加20分钟即可，第三次时加时延

2020-11-19 12:48 UTC, leonfancy approved these changes

2020-11-19 12:50 UTC, merged